AddTextEntry('0x0208F907', 'A non-stop musical journey from Los Angeles via the lab of Flying Lotus.')
AddTextEntry('0x02C4730C', 'Welcome to Los Angeles')
AddTextEntry('0x03CA3419', 'Garage East Los Angeles')
AddTextEntry('0x07B4308E', 'EXCLUSIVE STOCK<br>Only for our exclusive customers, a selection of vehicles you cant get anywhere else in Los Angeles!')
AddTextEntry('0x1C4C4DD5', 'You explored all of Los Angeles and Blaine County.')
AddTextEntry('0x3A6FB25E', 'Location, location, location. This huge apartment on the edge of Beverly Hills is in the heart of Los Angeles premium shopping district. Youll have that walk-in closet filled in no time! Shopping is really important to happiness.')
AddTextEntry('0x3A367CD5', 'Like every great American city, driving across Los Angeles is a matter of one long, straight road, fender-deep in mangled pedestrians. Breakneck time trial from the Los Angeles Memorial Coliseum to the Sisyphus Theatre.')
AddTextEntry('0x4D5FDCA9', 'Stunning deck and infinity pool with spectacular views of the city! If you have your heart set on an iconic 1960s-style Hollywood Hills home, look no further. Last house on coveted Ace Jones Drive so no prying eyes next door when the party really gets swinging!<BR><BR>"Lenny Avery - Always closing, never closed!"')
AddTextEntry('0x4DA9E130', '@cunningstuntacademy Suicidal? Dont get therapy. Get paid for it! Come by the academy today! Hollywood needs disposable guys like you. Become a stuntman today.')
AddTextEntry('0x5D7E740A', 'Hollywood Babylon')
AddTextEntry('0x5EBC827B', 'Mt Hollywood Dr')
AddTextEntry('0x787C9246', 'Hollywood Souvenirs - Tyler')
AddTextEntry('0x849C13E1', 'Hollywood Souvenirs - Al Di Napoli')
AddTextEntry('0x975A1B54', 'Lake Hollywood Est')
AddTextEntry('0x1546F1DF', 'Hollywood Souvenirs - Kerry')
AddTextEntry('0xA1C1AE1F', 'A Starlet In Hollywood')
AddTextEntry('0xA9B2553E', 'Hollywood Souvenirs - The Last Act')
AddTextEntry('0xA83E4A04', 'Hollywood Souvenirs - Mark')
AddTextEntry('0xAB59F800', 'Hollywood Souvenirs - Willie')
AddTextEntry('0xE26CF9AE', 'Radio Los Angeles: Hip hop stocks brooding')
AddTextEntry('0xEEF44D71', 'Radio Los Angeles announces new sound effects between songs.')
AddTextEntry('0xF7FA2DDC', 'Next Custom Radio Track')
AddTextEntry('BSS_BSTR_149', 'RadioLosAngeles')
AddTextEntry('RADIO_01_CLASS_ROCK', 'Los Angeles Rock Radio')
AddTextEntry('RADIO_03_HIPHOP_NEW', 'Radio Los Angeles')
AddTextEntry('WVINE', 'West Hollywood')
AddTextEntry('0x1C9EC441', 'Hollywood Sign')
AddTextEntry('NCHU', 'Port Hueneme')
AddTextEntry('ROCKF', 'Beverly Hills')
AddTextEntry('TONGVAH', 'Tongva Hills')
AddTextEntry('TONGVAV', 'Tongva Valley')
AddTextEntry('0x00280626', 'Hollywood Hills')
AddTextEntry('0x0FE0955F', 'Apt: Santa Monica Blvd 18')
AddTextEntry('0x9FB22D42', 'SANTA MONICA BOULEVARD<br>BEVERLY HILLS<br>LOS ANGELES')
AddTextEntry('0x13F01A9E', 'Garage: 634 Santa Monica Blvd')
AddTextEntry('0x21DD75BD', 'Santa Monica Blvd')
AddTextEntry('0xC8690C80', 'Santa Monica Fwy')
AddTextEntry('0xE9A28970', 'Santa Monica Pier')
AddTextEntry('CM_LOC_5', 'Santa Monica Pier')
AddTextEntry('DECL_P0_10_8', 'Santa Monica Pier T-Shirt')
AddTextEntry('DECL_P0_10_9', 'Los Angeles T-Shirt')
AddTextEntry('DELBE', 'Santa Monica Beach')
AddTextEntry('0x52059F21', 'California Sightseer')
AddTextEntry('CARBONIZ', 'California')
AddTextEntry('EMSTR_469', 'sales@southerncaliforniasuperautos.com')
AddTextEntry('EMSTR_641', 'events@SouthernCaliforniaSuperAutos.com')
AddTextEntry('EMSTR_642', '- Southern California Super Autos')
AddTextEntry('FMMC_MPM_TY122', 'California Flight School')
AddTextEntry('SANAND', 'California')
AddTextEntry('0x26E11637', 'California')
AddTextEntry('0x52059F21', 'California Sightseer')
AddTextEntry('CELL_148', 'Beverly')
AddTextEntry('CM_STOBEV', 'Beverly')
AddTextEntry('ROCKF', 'Beverly Hills')
AddTextEntry('0x73E60E8E', 'Beverly Hills')
AddTextEntry('0x99FB704A', '- The Beverly Hills Hotel')
AddTextEntry('0xDC95708A', 'Gauntlet - Beverly Hills')
AddTextEntry('ACCNA_H_RH', 'Beverly Hills Hospital')
AddTextEntry('ACCNA_PD_RH', 'Beverly Hills PD Bail')
AddTextEntry('MGCR_6', 'Venice Canals')
AddTextEntry('VCANA', 'Venice Canals')
AddTextEntry('YACHT_LOC_3', 'Venice Beach')
AddTextEntry('YACHT_LOC_4', 'Los Angeles International Airport')
AddTextEntry('YACHT_LOC_1', 'Port Hueneme')
AddTextEntry('0x0974CF3F', '- Venice Apartments')
AddTextEntry('0x7F30BAB5', '- Venice Beach')
AddTextEntry('RGLEN', 'Encino')
AddTextEntry('SELF_F3', 'West coast')
AddTextEntry('S_MO_01', 'West Coast Customs')
AddTextEntry('S_MO_05', 'West Coast Customs')
AddTextEntry('S_MO_06', 'West Coast Customs')
AddTextEntry('S_MO_08', 'West Coast Customs')
AddTextEntry('TAT_FM_MODDED', 'West Coast Customs')
AddTextEntry('TORSO_P2_0_10', 'West Coast Classics T-Shirt')
AddTextEntry('0x3F5E6148', 'West Coast Customs')
AddTextEntry('0x67B3089A', 'West Coast Customs')
AddTextEntry('0xEBCFBA08', 'West Coast Customs')
AddTextEntry('ACCNA_CARMOD', 'West Coast Customs')
AddTextEntry('ACCNA_VCLEAN', 'West Coast Customs')
AddTextEntry('BLIP_72', 'West Coast Customs')
AddTextEntry('CELL_E_209', 'West Coast Customs')
AddTextEntry('CELL_E_264', 'West Coast Customs')
AddTextEntry('EMSTR_387', 'West Coast Customs')
AddTextEntry('EMSTR_389', 'West Coast Customs')
AddTextEntry('EMSTR_389', '- West Coast Customs')
AddTextEntry('RADIO_05_TALK_01', 'West Coast Talk Radio')
AddTextEntry('PROP_EARNED_CMSH', 'West Coast Customs earnings')
AddTextEntry('PROP_BOUGHT_CMSH', 'West Coast Customs purchased')
AddTextEntry('PN_CMSH', 'West Coast Customs')
AddTextEntry('FM_IHELP_BST', 'You can buy Bullet Proof Tires at West Coast Customs ~BLIP_CAR_MOD_SHOP~')
AddTextEntry('FM_CTUT_MOD', 'Go to West Coast Customs.')
AddTextEntry('FM_CTUT_LLS', 'Leave West Coast Customs.')
AddTextEntry('RADIO_09_HIPHOP_OLD', 'West Coast Classics')
AddTextEntry('RADIO_05_TALK_01', 'West Coast Talk Radio')
AddTextEntry('RADIO_09_HIPHOP_OLD', 'West Coast Classics')
AddTextEntry('RADIO_18_90S_ROCK', 'Hollywood Boulevard Radio')
AddTextEntry('0x7F30BAB5', '- Venice Beach')
AddTextEntry('BEACH', 'Venice Beach')
AddTextEntry('EMSTR_399', 'Los Angeles Golf Club')
AddTextEntry('EMSTR_401', '- Los Angeles Golf Club')
AddTextEntry('EMSTR_642', '- Southern California Super Autos')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')
AddTextEntry('watrft', 'watrft')

